# Generated by Django 4.2.3 on 2023-07-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_game_uploaded_alter_game_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
