# Generated by Django 4.2.3 on 2023-07-25 15:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0015_librarygame'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='librarygame',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='librarygame',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='librarygame',
            name='user',
        ),
    ]
