# Generated by Django 4.2.3 on 2023-07-25 17:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0016_alter_librarygame_unique_together_librarygame_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='purchaser',
        ),
        migrations.AddField(
            model_name='game',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='LibraryGame',
        ),
    ]
