# Generated by Django 4.2.3 on 2023-08-02 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0017_remove_game_purchaser_game_users_delete_librarygame'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='uploader',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='uploader', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='users',
            field=models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
